name: macOS cross compiler

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - $default-branch
      - podock

  pull_request:
    branches:
      - $default-branch

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Building ...
        run: |
          echo "MACOS_SDK_TARBALL_PATH=$PWD/macos-cross-compiler/osxcross/tarballs/MacOSX10.10.sdk.tar.xz" >>"$GITHUB_ENV"
          echo "SRC_TARBALL_PATH=$PWD/macos-cross-compiler-src.tar.xz" >>"$GITHUB_ENV"
          echo "OUT_TARBALL_PATH=$PWD/macos-cross-compiler/osxcross/macos-cross-compiler.tar.xz" >>"$GITHUB_ENV"

          cat <<'EOF' >"$PWD/action-ci-build.sh"
          install -d $MACOS_CROSS_COMPILER/osxcross
          cd $MACOS_CROSS_COMPILER || exit
          git clone https://github.com/LiangchengJ/osxcross.git && cd osxcross || exit

          # picked this version as they work well with godot-rust, feel free to change
          git checkout 7c090bd8cd4ad28cf332f1d02267630d8f333c19

          sudo cp /root/MacOSX10.10.sdk.tar.xz $MACOS_CROSS_COMPILER/osxcross/tarballs/
          UNATTENDED=yes OSX_VERSION_MIN=10.7 ./build.sh && ./build_gcc.sh

          cd /workspace || exit
          tar -cJf macos-cross-compiler-src.tar.xz macos-cross-compiler

          cd $MACOS_CROSS_COMPILER/osxcross || exit
          mv target macos-cross-compiler
          tar -cJf macos-cross-compiler.tar.xz macos-cross-compiler
          EOF

          exec docker run -v "$PWD:/workspace" \
              -e MACOS_CROSS_COMPILER=/workspace/macos-cross-compiler \
              --entrypoint=bash "liangchengj/macos-cross-compiler-builder" -ex "/workspace/action-ci-build.sh"
        shell: bash

      - name: Publish compiler source artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS Cross Compiler Source
          path: ${{ env.SRC_TARBALL_PATH }}

      - name: Publish compiler artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS Cross Compiler
          path: ${{ env.OUT_TARBALL_PATH }}

      - name: Publish sdk artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS SDK
          path: ${{ env.MACOS_SDK_TARBALL_PATH }}
